// <auto-generated />
using System;
using BugraLife.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugraLife.Migrations
{
    [DbContext(typeof(BugraLifeDBContext))]
    [Migration("20251214145045_db_olusuturuldu")]
    partial class db_olusuturuldu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BugraLife.Models.WebSite", b =>
                {
                    b.Property<int>("website_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("website_id"));

                    b.Property<string>("website_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("website_id");

                    b.ToTable("WebSites");
                });

            modelBuilder.Entity("BugraLife.Models.WebSitePassword", b =>
                {
                    b.Property<int>("websitepassword_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("websitepassword_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("website_id")
                        .HasColumnType("int");

                    b.Property<string>("websitepassword_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("websitepassword_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("websitepassword_username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("websitepassword_id");

                    b.HasIndex("website_id");

                    b.ToTable("WebSitePasswords");
                });

            modelBuilder.Entity("BugraLife.Models.WebSitePassword", b =>
                {
                    b.HasOne("BugraLife.Models.WebSite", "WebSite")
                        .WithMany()
                        .HasForeignKey("website_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebSite");
                });
#pragma warning restore 612, 618
        }
    }
}
